# config/packages/nelmio_cors.yaml
nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['http://localhost:4200']  # Cambia esto si tu frontend está en otro dominio
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/':  # Solo se permite CORS para las rutas de tu API
            allow_origin: ['http://localhost:4200']  # Cambia esto si es necesario
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600
            expose_headers: ['Authorization']
