nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://localhost:4200']
        allow_methods: ['GET', 'POST', 'PATCH', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Accept']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['http://localhost:4200']
            allow_methods: ['GET', 'POST', 'PATCH', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Accept']
            max_age: 3600