security:
    # Configuración de hash para contraseñas
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User: 'auto' # Específicamente para tu entidad User

    # Proveedor de usuarios (usa la entidad User con el campo email)
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Configuración de los firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            jwt: ~
            # Eliminamos form_login porque usaremos JWT en su lugar
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login    # Mantengo esto por si aún quieres el login basado en formulario para otras partes
                check_path: app_login
                enable_csrf: true
            logout:
                path: app_logout
                target: app_home

    # Control de acceso
    access_control:
        # Permitir acceso público a las rutas de registro y login de la API
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: ROLE_USER }
        # Proteger todas las demás rutas bajo /api para usuarios autenticados
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        # Rutas existentes que puedes mantener si sigues usando el frontend Symfony
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/my-space, roles: ROLE_USER }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: PUBLIC_ACCESS }