<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAJ2JAd4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAJ2JAd4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAJ2JAd4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAJ2JAd4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAJ2JAd4\App_KernelDevDebugContainer([
    'container.build_hash' => 'AJ2JAd4',
    'container.build_id' => 'f87eed1e',
    'container.build_time' => 1743594560,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAJ2JAd4');
